### ISSUE TITLE
Adjacency table interpretation

### ISSUE THREAD

**Issue by Christsanutth** [marabouboy/FLAME#6]
Hi Alan,

I'm working on the same Hamster differential splicing project from @eltonjrv and I've had some issues interpreting the adjacency table from "[prefix].AdjacencyIncongruent.tsv". For example, when I compared the splice donor/acceptor sites from the exon combination with high read counts in "[prefix].QuantIncongruent.tsv" to "[prefix].AdjacencyIncongruent.tsv", there weren't any weights for those sites. However, those sites are present in "[prefix].PotentialSplice.tsv" with some short read counts supporting them. I referred to your paper and the guide on GitHub for interpretation, but I still don't quite understand. Could you point out how I might be misinterpreting this?

Example 1
"[prefix].AdjacencyIncongruent.tsv"
![Image](https://github.com/user-attachments/assets/1908e2ff-2ba5-4f9d-9576-14ef0ea70d4d)
"[prefix].AdjacencyIncongruent.tsv"
![Image](https://github.com/user-attachments/assets/754acfc9-6bf6-4eee-97c3-a66188ec4720)
"[prefix].PotentialSplice.tsv"
![Image](https://github.com/user-attachments/assets/1e9a9867-6099-4563-b1cb-e6c0e33a6a21)

Example 2
"[prefix].AdjacencyIncongruent.tsv"
![Image](https://github.com/user-attachments/assets/a18d2c9a-fc45-4f96-a7a2-812ec885fdc9)
"[prefix].AdjacencyIncongruent.tsv"
![Image](https://github.com/user-attachments/assets/40da3ab6-c8f7-4783-9f1f-c5f16788c8c7)
"[prefix].PotentialSplice.tsv"
![Image](https://github.com/user-attachments/assets/917829c5-6791-415c-8d68-3068fa9dda26)

Best, 
Chris

**Comment by marabouboy** [comment]
Hi Chris,

This might be related to the issue that Elton brought up. 
I have found what was causing the error and I was gonna update that issue once I fixed the issue but it seems that the implementation required a bit more time.

The issue was due to the combination of three factors:
1. The input was of (what I assume) whole transcriptome sequencing i.e. massive amounts of reads.
2. The reference genome was massive. The single gene version was designed for ~10^5 bp "genome" sizes at maximum
3. If you have whole transcriptome, you'd assume you wouldn't run the single gene version which is (now in hindsight) a flawed assumption.

However, I have found where the error arose from and it had to do with normalization.
I implemented a harsh 0.1% representation of the whole dataset, but when your dataset is in the millions, the number of reads that needs to support the region becomes untenable.

Therefore to fix this issue, I am implementing a filtering where the finding of potential new exons and alternative splice paths will be normalized to any read that contain at least one canonical exon, if you have sequencing reads that splice but does not overlap with any canonical exon, my argument is that perhaps you have an entire new gene rather than alternative splicing.

I have developed a filtering step and I am currently in the testing phase of the fix.

All this explanation is to say that I will return to your issue once I have updated the FLAME script to close Elton's issue.
I will then test FLAME and observe if the same oddities exists within the given output files and return to this issue.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

Thank you for your prompt response. Let's see what comes out of the updated version.

Best,
Chris

**Comment by marabouboy** [comment]
Hi Chris,

I have updated the FLAME pipeline and hopefully this will solve the issue.
If not, let me know what the issue seems to be.

My recommendation when looking at the adjacency tables is to either generate a heatmap using R (ComplexHeatmap/pheatmap) or Python (Matplotlib).
If excel is the name of the game, I believe that there is a function in excel where you are allowed to color the cells based on their value, if you implement this coloring function and zoom out to the maximum, perhaps a pattern emerges.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

I have looked at the outputs from your updated pipeline and I'm still facing the same issue described earlier. Do you have any comments regarding this? How should I refer to "[prefix].QuantIncongruent.tsv" when interpreting the "[prefix].AdjacencyIncongruent.tsv" and "[prefix].PotentialSplice.tsv"?

Edited: my heat map looks like this 
![Image](https://github.com/user-attachments/assets/b4780d2d-7641-4d35-ba8b-5db35c16bf73)

Best, Chris

**Comment by marabouboy** [comment]
Hi Chris,

Ok, if the issue remains, lets talk about the output.

I see that your heatmap looks similar as to what I can create with Plcd4.
You can see that are a couple of spots where the value is above 0. 
If you follow the rows, you will find the donor and when you follow the columns you will find the acceptors.
Do note the row and column of "Below 1%" meaning that the donor and/or acceptor, respectively, is seemingly in many different kinds of splicing events.

When using the "QuantIncongruent.tsv", you will find the algorithms attempt at quantifying the transcripts, however, the values that span a range (Example 1: 21256593−21256672) could be a potentially novel exon. You then go to "PotentialSplice.tsv" and find the two values to estimate whether the splicing events is reasonable (Does it have the canonical splicing patterns? Does it have enough supportive reads? Does it have short-read support?). Based on this, you decide yourself if the novel exon/alternative splicing is seemingly real and you add it to your annotation file (GTF) and rerun the FLAME algorithm as all the reads containing this unidentified exon/alternative splicing will fall under "Annotated" and a exploration of novel exons/alternative splicing can be done.

Based on your attached heatmap, you have a potential novel exon/alternative splicing between 21256614−21256565 and 21256670−21256565, i.e. they have the same donor but different acceptors, meaning that an alternative splicing event should have occurred.
I think this heatmap is great and should contain most of the information that will help you decide novel exons/alternative splicing. 
All you have to do is simply follow the rows and the columns to determine the possible splicing event.
My only comment would be that you should have color gradient that is dynamic: From 0, to 1, to 500; from white, to blue, to red.
I can see that the heatmap was created in python with matplotlib and my experience with matplotlib is that the color gradient controls are either nonexistent or intuitive. I have attached an R version using ComplexHeatmap where you are allowed to manipulate color scales. Do note the values are log transformed (Natural log) as well as this is of Plcd4.

![Image](https://github.com/user-attachments/assets/5ea3bce1-b8ce-4339-ac9a-2396abcc6f06)

Let me know if this helped.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

Thank you for the thorough explanation. I understand how I should interpret "QuantIncongruent.tsv" and "PotentialSplice.tsv" together, as well as "AdjacencyIncongruent.tsv" and "PotentialSplice.tsv" together. However, I am still a bit confused about why the beginning/ending of the novel exons suggested in "QuantIncongruent.tsv" with high counts sometimes don't have any weight from "AdjacencyIncongruent.tsv" near the suggested splice donor/acceptor sites. Should they not be interpreted together?

Sorry for the many questions. I just want to be fully confident about how I should interpret them before I draw any conclusions.

Best, Chris

**Comment by marabouboy** [comment]
Hi Chris,

No problem. 
When we originally conceptualized and designed the algorithm we were well aware that the output could be confusing but we decided that we would rather overshare information rather than undershare the information since a researcher is better with too much data rather too little.

When looking at the Plcd4 I noticed something.
If you use the first number to look for columns and the second number to look for rows, do you then find the missing reads?
I might have confused which dimension represented which parameter in the instructions in the wiki.

I have attached an example where I have highlighted a possible novel exon/alternative splicing in Plcd4. The red is when I use the ending as column and the start as row. The yellow is when i use the ending as row and start as column. Orange is when they overlap. I got values at the far corner of the yellow intersection.

![Image](https://github.com/user-attachments/assets/670c839a-947d-493e-8cb9-38e5d6417add)

Try that and see if you can find your values.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

I have tried playing around with the dimensions and noticed that when I used the beginnings and ends of the exons suggested in "QuantIncongruent.tsv" to search for the columns and rows in "AdjacencyIncongruent.tsv" respectively, it started to make sense. Are the columns supposed to represent the beginnings of exons instead of the splice donor sites, and the rows represent the ends of the exons instead of the splice acceptor sites?

Another question regarding the PLCD4 data: the final novel exon 18 range suggested in multiple combinations in "QuantIncongruent.tsv" does not appear anywhere in "AdjacencyIncongruent.tsv" or "PotentialSplice.tsv". What does that imply?

Thank you for your help and patience with this matter.

Best, 
Chris

**Comment by marabouboy** [comment]
Hi Chris,

To answer your first question, yes. I think we termed it splice donor/acceptor site instead of exon beginning and end as each splicing even technically creates either an splicing donor+exon beginning or an splicing acceptor+exon end. Then we designed the program from the exon's perspective, i.e. that values represents the quantification of possible novel exons in "AdjacencyIncongruent.tsv".

For the second question, I am not entirely sure which "final novel exon 18" you are referring too, but based on the "PotentialSplice.tsv" file, I am assuming the two transcript isoforms connected to exon 3-16 as well as four potentially novel exons (Two before exon 3 and two after exon 16). Based on what I can see it seems that they fall outside of the window of the gene or the fall below 1% representation. This does not explicitly mean that the potential novel exon does not exist, it simply means that it probably did not pass some sort of threshold. Perhaps if you add the novel exons/alternative splicing patterns that you DO find in "AdjacencyIncongruent.tsv" and/or in "PotentialSplice" into the reference annotation file, the total number of reads will be renormalized, resulting in the last window's inclusion. If even this fails, FLAME is simply a helping tool and if you determine that the last splicing range is a real exon, you can simply force FLAME to acknowledge the exon by implementing the given coordinates into the reference annotation (GTF).

No problem with the help. 
Helping people in exchange for people actually using FLAME is a small price to pay.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

Thanks to your explanation, I was able to analyze the incongruent data, adjust the GTF file, and rerun the FLAME algorithm. Now that I’m beginning to make sense of the annotated data, I’d like to ask a couple of questions about specific numbers in the output files to ensure I’m interpreting them correctly:

1. How does the algorithm determine the weight in the "AdjacencyAnnotated.tsv" file and the count in "QuantAnnotated.tsv"?
2. Are these values direct representations of read counts from the sequencing data?
3. In my "QuantIncongruent.tsv", there is still one final exon whose range is not covered in either the "AdjacencyAnnotated.tsv" or "PotentialSplice.tsv". It seems to be the only element preventing those isoforms from becoming fully annotated. What would you recommend I do in this case?
![Image](https://github.com/user-attachments/assets/1500119a-e03d-4cff-b4de-faa287d81b90)

Thank you again for your guidance and support.

Best,
Chris

**Comment by marabouboy** [comment]
Hi Chris,

Let us go through them one by one:
1. The weight in "AdjacencyAnnotated.tsv" is simply counting the number of times each annotated exon is either used as an splicing donor or splicing acceptor (similar fashion to the "AdjacentIncongruent.tsv"), the count in the "QuantAnnotated.tsv" file is then based on entire isoforms rather than invidiual exons so in our [RNA article](https://rnajournal.cshlp.org/content/27/10/1127.full.pdf+html) the "AdjacencyAnnoated.tsv" is used for Figure 5, while "QuantAnnotated.tsv" is used for Figure 6.
2. Yes, though Adjacency and Quant varies in what they represent, as Adjacency counts the number of splicing events in the annotated exons and Quant counts the number of whole transcript isoforms.
3. It seems to be very recurrent and 90 exon length is seemingly reasonable. While I cannot make the decision for you, I recommend looking at the given coordinates, does it have the canonical splice signal? Since it is among the last exons, is it a full exon or are you looking at the 5' UTR? Does it have a stop codon as it's last codon? Is it close to a poly-A signal (Assuming eukaryotic genome and transcription)?
It is however odd that the range is present in all (from what I can see) of the top isoforms yet the range is not represented in "PotentialSplice.tsv" nor "AdjacencyIncongruent.tsv" (You wrote "AdjacencyAnnotated.tsv" but I am assuming you mean "AdjacencyIncongruent.tsv").

Hope this answers your questions and you're welcome.

Sincerely,
Alan

**Comment by marabouboy** [comment]
Hi Chris,

As there has yet to be a comment on this thread within a week, I am going to assume that you have gotten the answers you requested in this thread.
If I have misunderstood, you are more than welcome to comment/re-open the thread.
If there there is no misunderstanding and I have answered the questions you have, I will close this thread on Monday afternoon.

Thank you for using FLAME.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

I was waiting to report back after I had finished all the iterations using FLAME. I found that the coverage of annotated reads plateaued around 60%, which I think is a reasonable outcome given the available evidence. This seems to reflect the fact that many of the remaining incongruent reads lack sufficient support to be confidently annotated.

The issue I reported in my previous post—specifically, the discrepancy between the adjacency table and potential exon definitions—still persists. Additionally, I’ve observed that some splice signals suggested in "PotentialSplice.tsv" do not actually exist in the genome sequence. I managed to work around this by inspecting the genome directly, but I wanted to report it in case it’s something worth looking into.

Thank you again for your guidance and for developing such a helpful tool.

Best regards,
Chris

**Comment by marabouboy** [comment]
Hi Christian,

Glad to hear that you have used FLAME in the correct manner (i.e. in the iterative manner) and that you have seemingly been able to classify a majority of the sequencing reads.

As for the remaining issues, I am very interested in any type of improvement that I possible to implement. Assuming, of course, I am not taking up your time reporting the issues.
1. When you mention the discrepancy between AdjacencyTable and Potential Exons, I am assuming the discrepancy between AdjacencyIncongruent.tsv and PotentialExons.tsv. Could you be a bit more specific in exactly what type of discrepancy? It is not that the splice junctions (whether acceptors or donors) end up in "Below 1%"?
2. With regard to the splice signals, I am assuming that you are talking about the canonical splice junction signals GU/AG. That is odd, that should not occur since the algorithm simply extracts the position and looks for the position within the reference genome. Is there any pattern in when the splice signals miss? Perhaps it has to to with how python counts, i.e. is it shifted 1 base from an actual GU/AG?

Sincerely,
Alan

**Comment by Christsanutth** [comment]
> Hi Alan,
> 
> Thanks to your explanation, I was able to analyze the incongruent data, adjust the GTF file, and rerun the FLAME algorithm. Now that I’m beginning to make sense of the annotated data, I’d like to ask a couple of questions about specific numbers in the output files to ensure I’m interpreting them correctly:
> 
> 1. How does the algorithm determine the weight in the "AdjacencyAnnotated.tsv" file and the count in "QuantAnnotated.tsv"?
> 2. Are these values direct representations of read counts from the sequencing data?
> 3. In my "QuantIncongruent.tsv", there is still one final exon whose range is not covered in either the "AdjacencyAnnotated.tsv" or "PotentialSplice.tsv". It seems to be the only element preventing those isoforms from becoming fully annotated. What would you recommend I do in this case?
>    ![Image](https://github.com/user-attachments/assets/1500119a-e03d-4cff-b4de-faa287d81b90)
> 
> Thank you again for your guidance and support.
> 
> Best, Chris


Hi Alan,

To answer your questions—happy to do so, it's not a problem at all:

1. For example, in the third issue mentioned in the quoted comment, the suggested novel exon accounts for over 30% of the total read count among the incongruent reads. However, neither the beginning nor the end of that exon appears in any of the rows or columns of the adjacency table—the table ends before reaching those positions.

2. I haven’t been able to identify a consistent pattern with this issue, as it seems quite random. For instance, sometimes a splice signal is reported where there is no nearby signal, and other times it reports an AG when the adjacent signal is actually a GU. I don’t think this is a major problem since I always verify directly against the genome, but I found it a bit unusual and thought it was worth mentioning.

Also, I just thought of a few more questions: 

1. Assuming the genome data we're working with might not be 100% accurate, what does FLAME do with reads that don’t align or only partially align to the genome? Do we know how many reads fall into that category?
2. I’ve just compared the final output with the read coverage from our long-read sequencing data, and in most of our reads, six bases are missing from the beginning of one of the exons annotated in the original GTF file. Only about 10% of the reads actually cover those six bases. However, FLAME did not detect this discrepancy and instead mapped all reads to the exon start position defined in the GTF file. The alternative start site—six bases downstream—which is supported by approximately 90% of the reads, was not mentioned in any of FLAME’s output files. How can this be explained?

Best,
Chris

**Comment by marabouboy** [comment]
Hi Chris,

Lets go through the comments one at a time.

1. I went through the code and found the reason for why 427809790-427810080 is not accounted for in the adjacency matrix. The motivation why that position was not included is the unruliness of large matrices and its tendency to crash excel/google-sheet or whatever one uses to view tabular data. The mechanism is due to a harsh limit of distance from either the first exon in your reference to your first exon in your read (1st/1st), or the last exon in your reference to your last exon in your read (last/last). As the numeric distance between 1st/1st or last/last is unbounded, the distance could, in theory, allow for "infinite distance" between actual exons and potential exons. To avoid this, if you supply a reference annotation, the maximum distance from the 1st or last exon is your "--range" parameter (default being 20bp). This is the full explanation for why the discrepancy exists. If I remember correctly, that is why one needs to use all three files (AdjacencyIncongruent, PotentialSplice, and QuantIncongruent) in order to define a potentially novel exon as there does not seem to exist a perfect data form that supplies ALL relevant information, all in one go. At least not without other severe downsides, such as crashing ones MS Excel.
2. I have attempted to recreate the error and I do not seem to find a case. Could you give an example within Plcd4 where such an error arises? No, I am very grateful for the reporting of any inconsistencies so report away.

Additional questions:
1. Hmm... The reads that does not align to the genome, I cannot account for, since the splicing relies on the initial alignment run using minimap2 and developing an orthogonal aligner on par with minimap2 is a little beyond my abilities. Partial alignment, I am not sure as I had not tested this parameter. It is most likely dependent on how a) minimap2 determine what constitutes a major inconsistency (softclipping), a non-alignment, and allowable inconsistency (Nanopore basecalling algorithm "noise") and b) bedtools convert softclipped reads into BED coordinates.
2. Six bases is seemingly too small for the default parameters, more specifically the "--range" parameter. Once you have annotated the "major" exons, you could try running FLAME but having a smaller "--range" window to see if FLAME can start distinguishing this subtle change.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

Thanks for the explanation—that makes sense to me.

Regarding your second point, here are a couple of examples:
- At position 427789566, which is right next to an AG splice signal, FLAME reported a GU signal for the range 427789564–427789566.
- At position 427807014, which has an adjacent GU signal, FLAME reported no signal for the range 427807012–427807015.
- At position 427808300, which is next to an AG splice signal, FLAME also reported no signal for the range 427808298-427808301.

Also, I have one more question. Since the gene is longer than the read length of our ONT sequencing data, how does FLAME determine the read count for each full isoform? Are these counts simply inferred proportionally from the adjacency data in the AdjacencyAnnotated.tsv file? It seems like there’s no direct evidence linking, for example, exon 1 connected to exon 3 with exon 16 connected to exon 18 within the same isoform.

Best,
Chris

**Comment by marabouboy** [comment]
Hi Chris,

Good to hear that I am not just simply rambling and some sense was made.

Regarding the inconsistencies, I have attempted to recreate the positions within PotentialSplice.tsv and when I run FLAME on the Plcd4 gene, the PotentialSplice.tsv is giving the correct splice signal. Is this inconsistency due to the reference genome given? Or perhaps could it be a one-off? Perhaps run FLAME again, and if the error remains, we have at least a consistent manner to create the bug.

As for the second question, there is no inference made as FLAME is a deterministic system based on the input. If your gene is "split", then the mRNA molecule would be counted twice. If I had the ability to accurately infer complete splicing and full isoform determination through an algorithm, there would not be a "need" for ONT Longread sequencing in relation to splicing as you could get all the information through short RNA sequencing + this inference algorithm. 
Now, your question gives way to an interesting possible novel method for full-length determination using tagmentation with "random" sequences (probably a whitelist of accepted sequences) after cDNA synthesis together with an algorithm that would rebuild the original full mRNA. However, then the question becomes if there might be some issues with the RTase trying to synthesize a cDNA molecule >1MB. Something to think about.

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

If I understand your answer correctly, I can be confident that the read count for each isoform reflects the actual number of reads covering the full length of that isoform.

Regarding the splice signal reporting issue, I don’t believe it’s due to the reference genome, as the other information was reported correctly. I’ve also observed this issue across several iterations of FLAME. Is there anything I can do to help with troubleshooting?

Best,
Chris

**Comment by marabouboy** [comment]
Hi Chris,

Yes, all reads that align to the region given (in gene specific mode) according to minimap2 should have been counted. The only reason reads would not be counted is due to misalignment and/or due to "wrongly" annotated gtf file.

Hmmm, an inconsistent bug is among the hardest to deal with. Could you recall at what iteration the error arose? Did the error already arise from the first iteration or was it from a specific point onward? Or does the manner of which the splice signal error seem random?

Sincerely,
Alan

**Comment by Christsanutth** [comment]
Hi Alan,

The error did arise in the first iteration and persisted over the following rounds. I could not observe any patterns. Would you like me to email you some examples from our iteration?

Best,
Chris

**Comment by marabouboy** [comment]
Hi Chris,

Yes, if you could run a text example on your end where you clearly produce the error and then send me the same input file. Perhaps send the FLAME and the reference genome you are using just in case.

Thank you for helping with the issue.

Sincerely,
Alan

**Comment by eltonjrv** [comment]
Hi Alan,

Good to talk to you once again. 
Chris asked me to get in touch for continuing on this issue chain.
So, 
a) the FLAME version we're using is your last one, which you added the new -CANON flag, according to what we discussed on my issue #5 (already closed).
b) Th reference genome (GTF we're realying on) is this: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/668/045/GCF_003668045.3_CriGri-PICRH-1.0/GCF_003668045.3_CriGri-PICRH-1.0_genomic.gtf.gz
c) and the input bed file (from minimap2-mapped ONT reads) is that same one I shared with previously from google drive (from that same issue #5). Please let me know if you no longer have this file, so I can share again (I might have deleted from my Google Drive).

Thanks,
Elton

**Comment by marabouboy** [comment]
Hi Elton,

Good to hear from you.

I have attempted to recreate the error once again and I simply cannot recreate it.
Can I send you the files as input as well as the parameters I use for running FLAME?

I appreciate the time and energy both you and Chris are giving me to find this irritating, un-recreatable error.

Sincerely,
Alan
